- src/pages/docs/_meta.json
- src/pages/docs/terms.md
- src/terms
> docs: add terms of service

- src/globals.css
Sluice the gradient from pinkish to bluish.
License: MIT
> feat: pink first website header.

- src/pages/docs/index.mdx
- src/theme.config.jsx
Fixes links to cli and client from the welcome page and the edit this page links.
License: MIT
> fix: broken links and copy

- .github/workflows/deploy.yml
we are moving fast so lets deploy to prod when we merge PRs to main.
releas please wasn't generating release PRs for docs commits but i dont think we need a changelog here.
LETS GO!
License: MIT
> feat: deploy from main. drop release-please

- src/pages/docs/w3cli.md
- src/pages/docs/w3up-client.md
> fix: w3cli docs with wrong space and w3client with wrong method

- src/pages/docs/quickstart.md
Feel free to reject changes and I will drop those ones. They are mostly suggestions but would not scale to do 1 PR per suggestion
> fix: quickstart tweaks

- src/pages/docs/how-to/create-account.md
- src/pages/docs/how-to/retrieve.md
- src/pages/docs/how-to/upload.md
Some suggestions for How to section. Some MAY be personal opinions, but others are more typos related
> fix: how to section suggestions

- src/pages/docs/how-to/upload.md
Motivation:
* https://github.com/web3-storage/www/issues/42
> docs: src/pages/docs/how-to/upload.md fix broken links to old api docs from /docs/how-to/upload/

- src/pages/docs/how-to/_meta.json
- src/pages/docs/how-to/create-account.md
- src/pages/docs/how-to/create-space.md
Motivation:
* https://github.com/web3-storage/secrets/issues/39
* https://github.com/web3-storage/secrets/issues/38
Tactics
* the URL is called create-account but it talked about create space too. Both are useful so let's have one page for each.
> docs: add /docs/how-to/create-space.md and edit create-account.md

- src/pages/docs/how-to/upload.md
Motivation:
* https://github.com/web3-storage/secrets/issues/38
> docs: copy changes to /how-to/upload/

- src/app/page.tsx
> fix: is 5GiB not 10GiB

- src/pages/docs/concepts/architecture-options.md
- src/pages/docs/concepts/car.md
- src/pages/docs/concepts/ucans-and-web3storage.md
- src/pages/docs/concepts/upload-vs-store.md
- src/pages/docs/faq.md
- src/pages/docs/how-to/create-account.md
- src/pages/docs/how-to/create-space.md
- src/pages/docs/how-to/list.md
- src/pages/docs/how-to/receipts.md
- src/pages/docs/how-to/remove.md
- src/pages/docs/how-to/upload.md
- src/pages/docs/quickstart.md
- src/pages/docs/w3cli.md
- src/pages/docs/w3up-client.md
> fix: update docs

- src/app/page.tsx
It should point to console. Thanks to Jefferson Sankara for reporting!
License: MIT
> fix: update homepage start link

- src/components/code.tsx
Depends on changes @Gozala is making to the client.
1. https://github.com/web3-storage/w3up/pull/1120#pullrequestreview-1729707319
2. TBC for `space.save()`
> feat: update example

- src/pages/docs/_meta.json
- src/pages/docs/faq.md
- src/pages/docs/go-w3up.mdx
- src/pages/docs/how-to/remove.mdx
- src/pages/docs/how-to/retrieve.mdx
- src/pages/docs/how-to/upload.mdx
- src/pages/docs/w3cli.mdx
> feat: add docs for standalone binaries and Go client

- .github/workflows/deploy.yml
...pending it being upgraded to use the new API
> fix: temporarily disable add-to-web3

- package.json
- pnpm-lock.yaml
- src/pages/docs/index.mdx
- src/theme.config.jsx
get rid of "Nextra: the next docs builder" and other rough edges.
doesn't set a preview image, as link previews with a giant redundant image are uncool. When we have time to make custom images per page, then maaaaybe i'll allow it.
License: MIT
> fix: update metadata tags in head

- .github/workflows/deploy.yml
upgrade to add-to-web3 v3. `W3_PRINCIPAL` and `W3_PROOF` have been set as repo secrets.
License: MIT
> fix: bring back publish to web3.storage

- src/pages/docs/concepts/architecture-options.mdx
- src/pages/docs/concepts/ucans-and-web3storage.md
- src/pages/docs/how-to/upload.mdx
depends on https://github.com/web3-storage/w3up/pull/1276
> fix: memory store import

- .github/workflows/deploy.yml
- added missing PR write permission to sticky-pull-request-comment
> chore: migrate repo

- src/pages/docs/concepts/architecture-options.mdx
- src/pages/docs/concepts/car.md
- src/pages/docs/how-to/remove.mdx
- src/pages/docs/how-to/upload.mdx
v15 reduces the amount of code and additional dependencies required to be installed to make for better DX.
> feat: update docs for client v15
